export const stories = [
  {
    profileImg: "./assets/img-13.jpg",
    profileName: "Behance",
    title: [
      "Showcasing creative",
      "portfolios and projects",
      "from top designers",
    ],
    linkLabel: "Read more",
    linkSrc: "behance.net",
    storyImg: "./assets/img-14.jpg",
  },
  {
    profileImg: "./assets/img-15.jpg",
    profileName: "Dribbble",
    title: ["Inspiring design", "ideas and visual", "creations from experts"],
    linkLabel: "Discover",
    linkSrc: "dribbble.com",
    storyImg: "./assets/img-16.jpg",
  },
  {
    profileImg: "./assets/img-15.jpg",
    profileName: "Awwwards",
    title: ["Award-winning web", "design and development", "projects"],
    linkLabel: "Check It Out",
    linkSrc: "awwwards.com",
    storyImg: "./assets/img-17.jpg",
  },
  {
    profileImg: "./assets/img-18.jpg",
    profileName: "Adobe",
    title: ["Curated design", "inspiration for", "creative professionals"],
    linkLabel: "Adobe More",
    linkSrc: "adobe.com",
    storyImg: "./assets/img-19.jpg",
  },
  {
    profileImg: "./assets/img-20.jpg",
    profileName: "Creative Bloq",
    title: ["The latest in", "design trends", "and tutorials"],
    linkLabel: "Explore",
    linkSrc: "creativebloq.com",
    storyImg: "./assets/img-21.jpg",
  },
  {
    profileImg: "./assets/img-22.jpg",
    profileName: "Smashing Magazine",
    title: ["Practical tips", "for web designers", "and developers"],
    linkLabel: "Visit Site",
    linkSrc: "smashingmagazine.com",
    storyImg: "./assets/img-13.jpg",
  },
];
